/* BRPOL 2026 — textos do painel em português e inglês. Chave ausente em inglês cai no português.
   {nome} é substituído pelo valor correspondente. */
window.BRPOL_TEXTOS = {
pt: {
  'lingua.outra': 'English', 'lingua.dica': 'Mudar o idioma para inglês',
  'titulo.app': 'BRPOL 2026 · Instagram na campanha',
  'bloqueio.desc': 'Painel restrito do projeto BRPOL (UFRJ × NUS): Instagram na campanha eleitoral de 2026, com dados agregados.',
  'bloqueio.senha': 'Senha do painel', 'bloqueio.lembrar': 'Lembrar neste navegador',
  'bloqueio.abrir': 'Abrir', 'bloqueio.abrindo': 'Abrindo…',
  'bloqueio.embargo': 'Os resultados são preliminares e não podem ser divulgados antes da diplomação, em 18 de dezembro de 2026.',
  'erro.senha': 'Senha incorreta.', 'erro.abrir': 'Não foi possível abrir os dados ({msg}).',
  'erro.sem_arquivo': 'Arquivo de dados não encontrado.', 'erro.invalido': 'Arquivo de dados inválido.',
  'erro.iniciar': 'Erro ao iniciar: {msg}',
  'tema.auto': 'Tema: automático', 'tema.dark': 'Tema: escuro', 'tema.light': 'Tema: claro', 'tema.dica': 'Alternar tema claro/escuro',
  'sair': 'Sair', 'sair.dica': 'Esquecer a senha neste navegador',
  'rodape': 'Fontes: Meta Content Library (posts do Instagram), Meta Ad Library (anúncios) e TSE (candidaturas). Painel restrito aos pesquisadores do projeto; resultados preliminares, não divulgar antes de 18/12/2026.',
  'sub': 'Atualizado em {data} · posts de {de} a {ate} · fase {fase}',
  'fase.0': '0 — descritiva',
  'ver_tabela': 'Ver tabela', 'ocultar_tabela': 'Ocultar tabela',
  'setas': 'Use as setas para percorrer os valores',
  'semana_de': 'Semana {s}', 'todas_semanas': 'Todas as semanas',
  'intervalo': '{a} a {b}', 'e': ' e ', 'menos10': 'Menos de 10 posts.',
  'posts': 'Posts', 'contas': 'Contas', 'dia': 'Dia', 'semana': 'Semana', 'todos': 'Todos', 'todas': 'Todas',
  'mediana': 'Mediana', 'parcela': 'Parcela', 'cargo': 'Cargo', 'uf': 'UF', 'campo': 'Campo', 'partido': 'Partido',

  'aba.geral': 'Visão geral', 'aba.perfis': 'Perfis', 'aba.engajamento': 'Engajamento', 'aba.temas': 'Temas e menções',
  'aba.conversa': 'Conversa pública', 'aba.anuncios': 'Anúncios', 'aba.metodo': 'Cobertura e método',

  'seg.lula': 'Coligação de Lula', 'seg.lula.curto': 'Lula',
  'seg.pl': 'Coligação do PL', 'seg.pl.curto': 'PL',
  'seg.outra_presidencial': 'Outras candidaturas presidenciais', 'seg.outra_presidencial.curto': 'Outras presid.',
  'seg.sem_presidencial': 'Partidos sem candidato a presidente', 'seg.sem_presidencial.curto': 'Sem presid.',
  'seg.partido': 'Contas de partidos', 'seg.partido.curto': 'Partidos',
  'seg.veiculo': 'Veículos de notícia', 'seg.veiculo.curto': 'Veículos',
  'seg.sem_casamento': 'Sem casamento com o TSE', 'seg.sem_casamento.curto': 'Sem casamento',
  'seg.sem_campo': 'Candidatos sem campo', 'seg.sem_campo.curto': 'Sem campo',

  'cargo.todos': 'Todos os cargos', 'cargo.presidente': 'Presidente', 'cargo.governador': 'Governador',
  'cargo.senador': 'Senador', 'cargo.dep_federal': 'Deputado federal', 'cargo.dep_estadual': 'Deputado estadual ou distrital',
  'cargo.outro': 'Outro cargo', 'cargo.sem_cargo': 'Sem cargo no "pago por"',
  'tse.DEPUTADO ESTADUAL': 'Deputado estadual', 'tse.DEPUTADO FEDERAL': 'Deputado federal', 'tse.DEPUTADO DISTRITAL': 'Deputado distrital',
  'tse.SENADOR': 'Senador', 'tse.GOVERNADOR': 'Governador', 'tse.PRESIDENTE': 'Presidente',
  'tse.MASCULINO': 'Masculino', 'tse.FEMININO': 'Feminino', 'tse.BRANCA': 'Branca', 'tse.PARDA': 'Parda', 'tse.PRETA': 'Preta',
  'tse.INDÍGENA': 'Indígena', 'tse.AMARELA': 'Amarela', 'tse.NÃO INFORMADO': 'Não informado', 'tse.NÃO DIVULGÁVEL': 'Não divulgável',

  'metrica.curtidas': 'Curtidas', 'metrica.comentarios': 'Comentários', 'metrica.views': 'Visualizações',
  'formato.video': 'Vídeo', 'formato.foto': 'Foto', 'formato.carrossel': 'Carrossel', 'formato.story': 'Story',
  'grupo.todos': 'Todos', 'grupo.candidato': 'Candidatos', 'grupo.partido': 'Partidos',
  'grupo.veiculo_nacional': 'Veículos nacionais', 'grupo.veiculo_regional': 'Veículos regionais',
  'grupo1.candidato': 'Candidato', 'grupo1.partido': 'Partido', 'grupo1.veiculo_nacional': 'Veículo nacional', 'grupo1.veiculo_regional': 'Veículo regional',
  'fonte.varredura': 'varredura', 'fonte.semanal': 'semanal', 'fonte.provisoria': 'provisória (captura diária)',
  'lado.extrema_esquerda': 'extrema-esquerda', 'lado.esquerda': 'esquerda', 'lado.centro_esquerda': 'centro-esquerda',
  'lado.centro': 'centro', 'lado.centro_direita': 'centro-direita', 'lado.direita': 'direita', 'lado.extrema_direita': 'extrema-direita',
  'lado.sem_classificacao': 'sem classificação',

  'tema.economy': 'Economia', 'tema.security': 'Segurança', 'tema.health_education': 'Saúde e educação',
  'tema.environment': 'Meio ambiente', 'tema.morality_values': 'Moral e valores', 'tema.foreign_policy': 'Política externa',
  'alvo.bolsonaro': 'Bolsonaro (qualquer)',
  'consulta.G1': 'presidenciáveis e STF', 'consulta.G2': 'rótulos políticos e presidenciáveis menores',
  'consulta.G3': 'eleição e voto', 'consulta.G4': 'candidaturas',
  'plataforma.facebook,instagram': 'Facebook e Instagram', 'plataforma.instagram': 'Só Instagram', 'plataforma.facebook': 'Só Facebook',
  'publico.female': 'Mulheres', 'publico.male': 'Homens', 'publico.unknown': 'Não informado',
  'regiao.fora do Brasil': 'Fora do Brasil', 'regiao.desconhecida': 'Desconhecida',

  'marco.propaganda': 'propaganda', 'marco.hgpe': 'horário eleitoral', 'marco.turno1': '1º turno', 'marco.turno2': '2º turno',
  'banda.sem': 'sem coleta', 'banda.prov': 'provisório',

  'geral.k_posts': 'Posts no censo', 'geral.k_posts_det': 'únicos, de contas conferidas',
  'geral.k_contas_det': '{c} candidatos · {p} partidos · {v} veículos',
  'geral.k_dias': 'Dias com coleta', 'geral.k_dias_det': 'de {n}, de {de} a {ate}', 'geral.k_semanas': 'Semanas',
  'geral.aviso_sem': 'Sem dados de {faixas}: a semana ainda não foi baixada.',
  'geral.aviso_prov': 'De {d} em diante, os posts vêm da captura diária das 20h30 e ficam provisórios até a semanal.',
  'geral.g1': 'Posts por dia das contas de candidatos, por campo',
  'geral.g1_leg': 'Campo é a coligação presidencial do partido do candidato (dados do TSE). Dia UTC da publicação.',
  'geral.g1_nota': 'Brasília é UTC−3: o dia UTC começa às 21h do dia anterior.',
  'geral.g2': 'Posts por dia dos veículos de notícia', 'geral.g2_leg': 'Veículos nacionais e regionais do censo.',
  'geral.g3': 'Contas de candidatos que publicaram no dia', 'geral.g3_leg': 'Quantas contas de candidatos do censo tiveram ao menos um post.',
  'geral.ativas': 'Contas ativas',
  'geral.semanas': 'Semanas de publicação',
  'geral.semanas_leg': 'Semanas de domingo a sábado; a primeira começa no sábado 15/08, linha de base antes da propaganda.',
  'geral.fonte': 'Fonte',

  'perfis.busca': 'Buscar', 'perfis.busca_ph': 'Nome ou usuário', 'perfis.busca_aria': 'Buscar conta',
  'perfis.tipo': 'Tipo de conta', 'perfis.ordenar': 'Ordenar por', 'perfis.nome': 'Nome',
  'perfis.ord_curtidas': 'Mediana de curtidas', 'perfis.ord_comentarios': 'Mediana de comentários', 'perfis.ord_views': 'Mediana de visualizações',
  'perfis.card': 'Contas do censo',
  'perfis.card_leg': 'Clique numa conta para ver a ficha. Medianas por post na observação base (7 a 32 dias de vida), só com 10 posts ou mais; stories ficam fora.',
  'perfis.col_conta': 'Conta', 'perfis.col_cargo': 'Cargo · UF', 'perfis.col_semana': 'Por semana',
  'perfis.contagem': '{n} de {total} contas', 'perfis.mais': 'Mostrar mais 50',
  'perfis.mesmo_cargo': 'mesmo cargo', 'perfis.mesmo_campo': 'mesmo campo',
  'perfis.pares': 'pares: {v}', 'perfis.pares_x': 'pares: {v} · {x}× a mediana',
  'perfis.fechar': 'Fechar', 'perfis.dias_post': '{n} dias com post',
  'perfis.pares_nota': 'Pares: {n} contas ({desc}).',
  'perfis.por_semana': 'Posts por semana de publicação', 'perfis.formatos': 'Formatos',
  'perfis.temas': 'Temas do dicionário: parcela dos posts que cita cada tema',
  'perfis.esta': 'Esta conta', 'perfis.med_pares': 'Mediana dos pares',
  'perfis.temas_nota': 'Traço vertical: mediana dos pares. Dicionário semente, ainda sem validação humana.',
  'perfis.hashtags': 'Hashtags mais usadas (3 posts ou mais)',

  'eng.metrica': 'Métrica', 'eng.semana': 'Semana de publicação',
  'eng.aviso': 'O engajamento é medido na observação base: o post visto de 7 a 32 dias depois de publicado. A idade muda de semana para semana (veja a tabela), por isso compare os campos dentro da mesma semana. Stories não têm curtidas nem comentários e ficam de fora. Medianas só com 10 posts ou mais.',
  'eng.quartis': '25% a 75%', 'eng.idade': 'Idade mediana na observação: {d} dias',
  'eng.g1': 'Mediana de {m} por post · semana {s}',
  'eng.g1_leg': 'Candidatos, {cargo}. A barra é a mediana; o traço fino vai do 1º ao 3º quartil.',
  'eng.g1_nota': 'Partidos e veículos de notícia, que têm outra escala, estão na tabela.',
  'eng.segmento': 'Segmento', 'eng.q1': '1º quartil', 'eng.q3': '3º quartil', 'eng.idade_col': 'Idade mediana (dias)',
  'eng.g2': 'Mediana de {m} por formato', 'eng.g2_leg': 'Candidatos, {cargo}, todas as semanas com observação base.',
  'eng.g2_nota': 'Partidos e veículos na tabela.', 'eng.formato': 'Formato',
  'eng.g3': 'Primeiras horas: mediana de {m} pela idade do post',
  'eng.g3_leg': 'Captura diária do próprio dia (20h30 de Brasília), todos os cargos. Cada post aparece uma vez, na idade em que foi visto.',
  'eng.g3_sem_views': 'As visualizações ainda não aparecem na captura das primeiras horas.',
  'eng.g3_vazio': 'Sem dados de visualização nessa captura.', 'eng.idade_curta': 'Idade',
  'eng.g4': 'Horário das publicações (Brasília)',
  'eng.g4_leg': 'Parcela dos posts de cada campo publicada em cada hora do dia, todas as semanas e cargos.', 'eng.hora': 'Hora',

  'temas.alvo': 'Menção ao longo do tempo', 'temas.hashtags_de': 'Hashtags de',
  'temas.aviso': 'Temas vêm da camada semente do dicionário do projeto (config/lexicon.yaml) e menções, de nomes e perfis dos presidenciáveis. É contagem de palavras, sem modelo e sem validação humana: um post que cita um tema pode falar dele de passagem. "Bolsonaro (qualquer)" inclui Flávio, Jair, Eduardo e Michelle.',
  'temas.citam': 'Posts que citam', 'temas.no_seg': 'Posts no segmento',
  'temas.mapa_temas': 'Temas · {s}', 'temas.mapa_temas_leg': 'Parcela dos posts de cada segmento que cita cada tema.',
  'temas.mapa_alvos': 'Menções · {s}', 'temas.mapa_alvos_leg': 'Parcela dos posts de cada segmento que cita cada nome.',
  'temas.linha': 'Posts que citam {a}, por semana', 'temas.linha_leg': 'Parcela dos posts de cada segmento. A última semana ainda é provisória.',
  'temas.linha_nota': 'Veículos de notícia em cinza escuro.',
  'temas.tags': 'Hashtags · {seg}', 'temas.tags_leg': '{s}. Hashtags com 10 posts ou mais, de 3 contas ou mais.',
  'temas.tags_vazio': 'Nenhuma hashtag passa do mínimo nesse recorte.',

  'conv.vazio': 'A linha de conversa ainda não foi consolidada.',
  'conv.k_posts': 'Posts na base', 'conv.k_posts_det': 'fora do censo, sem descartes',
  'conv.k_contas': 'Contas por semana', 'conv.k_contas_det': 'mediana de contas distintas',
  'conv.aviso': 'Posts sobre a eleição de contas fora do censo, achados por palavras-chave (consultas G1 a G4, docs/12). Tudo aqui é agregado por dia, consulta, termo ou hashtag; nada é mostrado por conta. As semanas entram 7 dias depois de terminar.',
  'conv.g1': 'Posts por dia na base da conversa', 'conv.g1_leg': 'Um post conta uma vez, mesmo que tenha casado com mais de uma consulta.',
  'conv.por_consulta': 'Por consulta',
  'conv.termos': 'Termos que mais casaram', 'conv.termos_leg': 'Termos das consultas encontrados no texto, como a busca da interface os lê (sem acento).',
  'conv.termo': 'Termo', 'conv.tags': 'Hashtags mais usadas', 'conv.tags_leg': 'Com 20 posts ou mais, de 5 contas ou mais.',

  'ads.vazio': 'Nenhum arquivo da Ad Library consolidado ainda.',
  'ads.anuncios': 'Anúncios', 'ads.paginas': '{n} páginas', 'ads.paginas_col': 'Páginas',
  'ads.gasto': 'Gasto declarado', 'ads.gasto_det': 'soma das faixas, em reais',
  'ads.impressoes': 'Impressões', 'ads.imp_sem_teto': '{n} anúncios com 1 milhão ou mais, contados pelo piso', 'ads.imp_det': 'soma das faixas',
  'ads.citam': 'Citam "Lula" no texto', 'ads.citam_det': 'os demais casaram em outro campo do anúncio',
  'ads.casados': 'Casados com o TSE', 'ads.casados_det': 'pelo nome do responsável ("pago por")',
  'ads.aviso': 'Anúncios que a busca por "{b}" na Ad Library retornou (baixados em {d}), com início de veiculação a partir de {ini}. É uma amostra por palavra-chave, não o total de anúncios políticos. Gasto e impressões vêm em faixas: a barra cheia vai até o piso e a parte clara até o teto.',
  'ads.gasto_curto': 'Gasto', 'ads.citam_lula': 'Citam Lula', 'ads.gasto_min': 'Gasto mín.', 'ads.gasto_max': 'Gasto máx.',
  'ads.g1': 'Gasto por campo do anunciante', 'ads.g1_leg': 'Campo da candidatura casada pelo nome no TSE.',
  'ads.g2': 'Quem usa o nome de Lula nos anúncios', 'ads.g2_leg': 'Parcela dos anúncios de cada campo com "Lula" no texto.',
  'ads.n_anuncios': '{n} anúncios',
  'ads.g3': 'Anúncios iniciados por dia, por campo', 'ads.g3_leg': 'Dia de início da veiculação. Anúncios sem casamento com o TSE ficam fora deste gráfico.',
  'ads.g4': 'Gasto por cargo', 'ads.g5': 'Plataformas',
  'ads.top': 'Maiores anunciantes', 'ads.top_leg': 'As 30 páginas com maior teto de gasto no recorte. Dados públicos da Ad Library.',
  'ads.pagina': 'Página', 'ads.publico_de': 'Público de', 'ads.todos': 'Todos os anúncios',
  'ads.g6': 'Quem viu: idade e gênero', 'ads.g6_leg': 'Parcela das impressões (ponto médio da faixa de cada anúncio).',
  'ads.g7': 'Onde foi visto', 'ads.g7_leg': 'Parcela das impressões por UF.',

  'met.nota': 'Barra: candidaturas com conta no censo. Traço: declararam Instagram ao TSE.',
  'met.registradas': 'Registradas', 'met.declarado': 'Instagram declarado', 'met.no_censo': 'No censo', 'met.grupo': 'Grupo',
  'met.k_reg': 'Candidaturas registradas', 'met.k_reg_det': 'presidente, governador, senador e deputados',
  'met.k_censo': 'No censo baixável', 'met.k_censo_det': '{p} das candidaturas',
  'met.cargo': 'Cobertura por cargo', 'met.cargo_leg': 'Parcela das candidaturas registradas no TSE que está no censo. Ao lado de cada grupo, o número de candidaturas.',
  'met.genero': 'Cobertura por gênero', 'met.genero_leg': 'Parcela das candidaturas no censo.',
  'met.raca': 'Cobertura por cor ou raça', 'met.raca_leg': 'Autodeclaração ao TSE; grupos com 10 candidaturas ou mais.',
  metodo: [
    ['O que é este painel', 'Um retrato agregado e descritivo do Instagram das candidaturas, partidos e veículos de notícia na campanha de 2026, atualizado a cada nova coleta. Esta é a fase 0: contagens, medianas e dicionários. As fases seguintes acrescentam rótulos por modelo, validados por amostra humana.'],
    ['De onde vêm os dados', [
      'Posts: Meta Content Library, exportação em CSV das contas baixáveis (25 mil seguidores ou selo de verificação) de candidatos, partidos e 130 veículos, conferidas contra o TSE.',
      'Semana de publicação baixada 7 dias depois de terminar (observação base). Desde 22/09, também uma captura do próprio dia às 20h30 de Brasília.',
      'Conversa pública: buscas por palavra-chave de contas fora do censo (consultas G1 a G4).',
      'Anúncios: Meta Ad Library, por busca de palavra-chave.',
      'Candidaturas, campo e coligações: arquivos públicos do TSE (14/09/2026).']],
    ['Como ler', [
      'Campo é a coligação presidencial do partido do candidato: aliança eleitoral, não ideologia.',
      'Dias em UTC, como nos filtros da Content Library; Brasília é UTC−3.',
      'Medianas e quartis aparecem só com 10 posts ou mais; abaixo disso, "—".',
      'Temas e menções são contagens por dicionário, sem modelo e sem validação.']],
    ['Ressalvas', [
      'O censo não é amostra aleatória: a cobertura é menor entre mulheres, candidatos pretos, pardos e indígenas, sem mandato e do Norte (gráficos acima).',
      'Engajamento depende da idade do post na observação; compare dentro da mesma semana.',
      'Cerca de 9% dos posts escondem as curtidas; o denominador de cada mediana é o número de posts com a métrica.',
      'A observação mede o que sobreviveu até a coleta, não tudo o que foi publicado.',
      'Nenhum resultado aqui é causal.']],
    ['O que não está aqui', 'Texto de post, identificador de post, links e mídia, identificadores internos da Meta e qualquer dado por conta na linha de conversa. Os dados brutos ficam só com os pesquisadores aprovados no projeto.'],
    ['Regras de uso', [
      'Painel restrito ao grupo do projeto; não repasse a senha.',
      'Nada é divulgado publicamente antes da diplomação, em 18/12/2026.',
      'Ao citar, indique a Meta Content Library e a Ad Library como fontes e o TSE para as candidaturas.']],
    ['Próximas fases', [
      'Sentimento, incivilidade e função do discurso (aclamação, ataque, defesa) por modelo, com validação humana.',
      'Quem fala de quem, com a postura (favorável, desfavorável, neutra) de cada menção.',
      'Tópicos por perfil e tópicos emergentes.',
      'Modelos de engajamento com efeito fixo de conta (razões de taxas e razões de chances).']],
  ],
},

en: {
  'lingua.outra': 'Português', 'lingua.dica': 'Switch the language to Portuguese',
  'titulo.app': 'BRPOL 2026 · Instagram in the campaign',
  'bloqueio.desc': "Restricted dashboard of the BRPOL project (UFRJ × NUS): Instagram in Brazil's 2026 election campaign, aggregated data.",
  'bloqueio.senha': 'Dashboard password', 'bloqueio.lembrar': 'Remember on this browser',
  'bloqueio.abrir': 'Open', 'bloqueio.abrindo': 'Opening…',
  'bloqueio.embargo': 'Results are preliminary and must not be made public before the certification of elected candidates (diplomação) on 18 December 2026.',
  'erro.senha': 'Wrong password.', 'erro.abrir': 'Could not open the data ({msg}).',
  'erro.sem_arquivo': 'Data file not found.', 'erro.invalido': 'Invalid data file.',
  'erro.iniciar': 'Startup error: {msg}',
  'tema.auto': 'Theme: auto', 'tema.dark': 'Theme: dark', 'tema.light': 'Theme: light', 'tema.dica': 'Toggle light/dark theme',
  'sair': 'Sign out', 'sair.dica': 'Forget the password on this browser',
  'rodape': "Sources: Meta Content Library (Instagram posts), Meta Ad Library (ads) and TSE, Brazil's electoral court (candidacies). Restricted to project researchers; preliminary results, not to be made public before 18 Dec 2026.",
  'sub': 'Updated {data} · posts from {de} to {ate} · phase {fase}',
  'fase.0': '0 — descriptive',
  'ver_tabela': 'Show table', 'ocultar_tabela': 'Hide table',
  'setas': 'Use the arrow keys to move through the values',
  'semana_de': 'Week of {s}', 'todas_semanas': 'All weeks',
  'intervalo': '{a}–{b}', 'e': ' and ', 'menos10': 'Fewer than 10 posts.',
  'posts': 'Posts', 'contas': 'Accounts', 'dia': 'Day', 'semana': 'Week', 'todos': 'All', 'todas': 'All',
  'mediana': 'Median', 'parcela': 'Share', 'cargo': 'Office', 'uf': 'State', 'campo': 'Bloc', 'partido': 'Party',

  'aba.geral': 'Overview', 'aba.perfis': 'Profiles', 'aba.engajamento': 'Engagement', 'aba.temas': 'Topics and mentions',
  'aba.conversa': 'Public conversation', 'aba.anuncios': 'Ads', 'aba.metodo': 'Coverage and method',

  'seg.lula': "Lula's coalition", 'seg.lula.curto': 'Lula',
  'seg.pl': 'PL coalition', 'seg.pl.curto': 'PL',
  'seg.outra_presidencial': 'Other presidential candidacies', 'seg.outra_presidencial.curto': 'Other pres.',
  'seg.sem_presidencial': 'Parties without a presidential candidate', 'seg.sem_presidencial.curto': 'No pres.',
  'seg.partido': 'Party accounts', 'seg.partido.curto': 'Parties',
  'seg.veiculo': 'News outlets', 'seg.veiculo.curto': 'Outlets',
  'seg.sem_casamento': 'Not matched to TSE', 'seg.sem_casamento.curto': 'Unmatched',
  'seg.sem_campo': 'Candidates without a bloc', 'seg.sem_campo.curto': 'No bloc',

  'cargo.todos': 'All offices', 'cargo.presidente': 'President', 'cargo.governador': 'Governor',
  'cargo.senador': 'Senator', 'cargo.dep_federal': 'Federal deputy', 'cargo.dep_estadual': 'State or district deputy',
  'cargo.outro': 'Other office', 'cargo.sem_cargo': 'No office in "paid for by"',
  'tse.DEPUTADO ESTADUAL': 'State deputy', 'tse.DEPUTADO FEDERAL': 'Federal deputy', 'tse.DEPUTADO DISTRITAL': 'District deputy',
  'tse.SENADOR': 'Senator', 'tse.GOVERNADOR': 'Governor', 'tse.PRESIDENTE': 'President',
  'tse.MASCULINO': 'Male', 'tse.FEMININO': 'Female', 'tse.BRANCA': 'White', 'tse.PARDA': 'Pardo (mixed race)', 'tse.PRETA': 'Black',
  'tse.INDÍGENA': 'Indigenous', 'tse.AMARELA': 'East Asian descent', 'tse.NÃO INFORMADO': 'Not reported', 'tse.NÃO DIVULGÁVEL': 'Not disclosed',

  'metrica.curtidas': 'Likes', 'metrica.comentarios': 'Comments', 'metrica.views': 'Views',
  'formato.video': 'Video', 'formato.foto': 'Photo', 'formato.carrossel': 'Carousel', 'formato.story': 'Story',
  'grupo.todos': 'All', 'grupo.candidato': 'Candidates', 'grupo.partido': 'Parties',
  'grupo.veiculo_nacional': 'National outlets', 'grupo.veiculo_regional': 'Regional outlets',
  'grupo1.candidato': 'Candidate', 'grupo1.partido': 'Party', 'grupo1.veiculo_nacional': 'National outlet', 'grupo1.veiculo_regional': 'Regional outlet',
  'fonte.varredura': 'sweep', 'fonte.semanal': 'weekly', 'fonte.provisoria': 'provisional (same-day capture)',
  'lado.extrema_esquerda': 'far left', 'lado.esquerda': 'left', 'lado.centro_esquerda': 'centre-left',
  'lado.centro': 'centre', 'lado.centro_direita': 'centre-right', 'lado.direita': 'right', 'lado.extrema_direita': 'far right',
  'lado.sem_classificacao': 'unclassified',

  'tema.economy': 'Economy', 'tema.security': 'Public security', 'tema.health_education': 'Health and education',
  'tema.environment': 'Environment', 'tema.morality_values': 'Morality and values', 'tema.foreign_policy': 'Foreign policy',
  'alvo.bolsonaro': 'Bolsonaro (any)',
  'consulta.G1': 'presidential candidates and Supreme Court', 'consulta.G2': 'political labels and minor presidential candidates',
  'consulta.G3': 'election and voting', 'consulta.G4': 'candidacies',
  'plataforma.facebook,instagram': 'Facebook and Instagram', 'plataforma.instagram': 'Instagram only', 'plataforma.facebook': 'Facebook only',
  'publico.female': 'Women', 'publico.male': 'Men', 'publico.unknown': 'Unknown',
  'regiao.fora do Brasil': 'Outside Brazil', 'regiao.desconhecida': 'Unknown',

  'marco.propaganda': 'campaigning', 'marco.hgpe': 'free TV airtime', 'marco.turno1': '1st round', 'marco.turno2': 'runoff',
  'banda.sem': 'no data', 'banda.prov': 'provisional',

  'geral.k_posts': 'Posts in the census', 'geral.k_posts_det': 'unique, from verified accounts',
  'geral.k_contas_det': '{c} candidates · {p} parties · {v} outlets',
  'geral.k_dias': 'Days with data', 'geral.k_dias_det': 'of {n}, {de} to {ate}', 'geral.k_semanas': 'Weeks',
  'geral.aviso_sem': 'No data for {faixas}: that week has not been downloaded yet.',
  'geral.aviso_prov': 'From {d} on, posts come from the same-day capture at 8:30 pm Brasília time and remain provisional until the weekly download.',
  'geral.g1': 'Daily posts by candidate accounts, by bloc',
  'geral.g1_leg': "Bloc is the presidential coalition of the candidate's party (TSE data). UTC day of publication.",
  'geral.g1_nota': 'Brasília is UTC−3: the UTC day starts at 9 pm the previous day.',
  'geral.g2': 'Daily posts by news outlets', 'geral.g2_leg': 'National and regional outlets in the census.',
  'geral.g3': 'Candidate accounts that posted each day', 'geral.g3_leg': 'Number of candidate accounts in the census with at least one post.',
  'geral.ativas': 'Active accounts',
  'geral.semanas': 'Publication weeks',
  'geral.semanas_leg': 'Weeks run Sunday to Saturday; the first starts on Saturday 15 Aug, a baseline day before campaigning began.',
  'geral.fonte': 'Source',

  'perfis.busca': 'Search', 'perfis.busca_ph': 'Name or username', 'perfis.busca_aria': 'Search account',
  'perfis.tipo': 'Account type', 'perfis.ordenar': 'Sort by', 'perfis.nome': 'Name',
  'perfis.ord_curtidas': 'Median likes', 'perfis.ord_comentarios': 'Median comments', 'perfis.ord_views': 'Median views',
  'perfis.card': 'Census accounts',
  'perfis.card_leg': 'Click an account to see its profile. Per-post medians at the base observation (7 to 32 days after posting), only with 10 or more posts; stories excluded.',
  'perfis.col_conta': 'Account', 'perfis.col_cargo': 'Office · State', 'perfis.col_semana': 'Per week',
  'perfis.contagem': '{n} of {total} accounts', 'perfis.mais': 'Show 50 more',
  'perfis.mesmo_cargo': 'same office', 'perfis.mesmo_campo': 'same bloc',
  'perfis.pares': 'peers: {v}', 'perfis.pares_x': 'peers: {v} · {x}× the median',
  'perfis.fechar': 'Close', 'perfis.dias_post': '{n} days with posts',
  'perfis.pares_nota': 'Peers: {n} accounts ({desc}).',
  'perfis.por_semana': 'Posts per publication week', 'perfis.formatos': 'Formats',
  'perfis.temas': 'Dictionary topics: share of posts mentioning each topic',
  'perfis.esta': 'This account', 'perfis.med_pares': 'Peer median',
  'perfis.temas_nota': 'Vertical tick: peer median. Seed dictionary, not yet validated by human coders.',
  'perfis.hashtags': 'Most used hashtags (3 or more posts)',

  'eng.metrica': 'Metric', 'eng.semana': 'Publication week',
  'eng.aviso': 'Engagement is measured at the base observation: the post as seen 7 to 32 days after publication. Post age differs from week to week (see the table), so compare blocs within the same week. Stories have no likes or comments and are excluded. Medians only with 10 or more posts.',
  'eng.quartis': '25th–75th percentile', 'eng.idade': 'Median age at observation: {d} days',
  'eng.g1': 'Median {m} per post · week of {s}',
  'eng.g1_leg': 'Candidates, {cargo}. The bar is the median; the thin line spans the 1st to 3rd quartile.',
  'eng.g1_nota': 'Parties and news outlets, which are on a different scale, are in the table.',
  'eng.segmento': 'Segment', 'eng.q1': '1st quartile', 'eng.q3': '3rd quartile', 'eng.idade_col': 'Median age (days)',
  'eng.g2': 'Median {m} by format', 'eng.g2_leg': 'Candidates, {cargo}, all weeks with a base observation.',
  'eng.g2_nota': 'Parties and outlets in the table.', 'eng.formato': 'Format',
  'eng.g3': 'First hours: median {m} by post age',
  'eng.g3_leg': 'Same-day capture (8:30 pm Brasília time), all offices. Each post appears once, at the age it was observed.',
  'eng.g3_sem_views': 'Views are not yet available in the first-hours capture.',
  'eng.g3_vazio': 'No view data in this capture.', 'eng.idade_curta': 'Age',
  'eng.g4': 'Posting time (Brasília)',
  'eng.g4_leg': "Share of each bloc's posts published in each hour of the day, all weeks and offices.", 'eng.hora': 'Hour',

  'temas.alvo': 'Mention over time', 'temas.hashtags_de': 'Hashtags from',
  'temas.aviso': 'Topics come from the seed layer of the project dictionary (config/lexicon.yaml), and mentions from the names and handles of the presidential candidates. These are word counts, with no model and no human validation: a post that mentions a topic may only touch on it. "Bolsonaro (any)" includes Flávio, Jair, Eduardo and Michelle.',
  'temas.citam': 'Posts mentioning', 'temas.no_seg': 'Posts in segment',
  'temas.mapa_temas': 'Topics · {s}', 'temas.mapa_temas_leg': "Share of each segment's posts mentioning each topic.",
  'temas.mapa_alvos': 'Mentions · {s}', 'temas.mapa_alvos_leg': "Share of each segment's posts mentioning each name.",
  'temas.linha': 'Posts mentioning {a}, by week', 'temas.linha_leg': "Share of each segment's posts. The last week is still provisional.",
  'temas.linha_nota': 'News outlets in dark grey.',
  'temas.tags': 'Hashtags · {seg}', 'temas.tags_leg': '{s}. Hashtags with 10 or more posts from 3 or more accounts.',
  'temas.tags_vazio': 'No hashtag reaches the minimum in this selection.',

  'conv.vazio': 'The public conversation line has not been consolidated yet.',
  'conv.k_posts': 'Posts in the base', 'conv.k_posts_det': 'outside the census, after exclusions',
  'conv.k_contas': 'Accounts per week', 'conv.k_contas_det': 'median of distinct accounts',
  'conv.aviso': 'Election-related posts from accounts outside the census, found by keyword (queries G1 to G4, docs/12). Everything here is aggregated by day, query, term or hashtag; nothing is shown per account. Weeks are added 7 days after they end.',
  'conv.g1': 'Daily posts in the conversation base', 'conv.g1_leg': 'Each post counts once, even if it matched more than one query.',
  'conv.por_consulta': 'By query',
  'conv.termos': 'Most matched terms', 'conv.termos_leg': 'Query terms found in the text, as the search interface reads them (accents removed).',
  'conv.termo': 'Term', 'conv.tags': 'Most used hashtags', 'conv.tags_leg': 'With 20 or more posts from 5 or more accounts.',

  'ads.vazio': 'No Ad Library file consolidated yet.',
  'ads.anuncios': 'Ads', 'ads.paginas': '{n} pages', 'ads.paginas_col': 'Pages',
  'ads.gasto': 'Reported spend', 'ads.gasto_det': 'sum of ranges, in Brazilian reais',
  'ads.impressoes': 'Impressions', 'ads.imp_sem_teto': '{n} ads with 1 million or more, counted at the lower bound', 'ads.imp_det': 'sum of ranges',
  'ads.citam': 'Mention "Lula" in the text', 'ads.citam_det': 'the rest matched on another ad field',
  'ads.casados': 'Matched to TSE', 'ads.casados_det': 'by the name in "paid for by"',
  'ads.aviso': 'Ads returned by an Ad Library search for "{b}" (downloaded {d}), with delivery starting on or after {ini}. This is a keyword sample, not all political ads. Spend and impressions come as ranges: the solid bar reaches the lower bound and the light part the upper bound.',
  'ads.gasto_curto': 'Spend', 'ads.citam_lula': 'Mention Lula', 'ads.gasto_min': 'Min. spend', 'ads.gasto_max': 'Max. spend',
  'ads.g1': 'Spend by advertiser bloc', 'ads.g1_leg': 'Bloc of the candidacy matched by name in TSE records.',
  'ads.g2': "Who uses Lula's name in ads", 'ads.g2_leg': 'Share of each bloc\'s ads with "Lula" in the text.',
  'ads.n_anuncios': '{n} ads',
  'ads.g3': 'Ads started per day, by bloc', 'ads.g3_leg': 'Delivery start day. Ads not matched to TSE are left out of this chart.',
  'ads.g4': 'Spend by office', 'ads.g5': 'Platforms',
  'ads.top': 'Top advertisers', 'ads.top_leg': 'The 30 pages with the highest upper-bound spend in this selection. Public Ad Library data.',
  'ads.pagina': 'Page', 'ads.publico_de': 'Audience of', 'ads.todos': 'All ads',
  'ads.g6': 'Who saw them: age and gender', 'ads.g6_leg': "Share of impressions (midpoint of each ad's range).",
  'ads.g7': 'Where they were seen', 'ads.g7_leg': 'Share of impressions by state.',

  'met.nota': 'Bar: candidacies with an account in the census. Tick: declared an Instagram account to TSE.',
  'met.registradas': 'Registered', 'met.declarado': 'Declared Instagram', 'met.no_censo': 'In census', 'met.grupo': 'Group',
  'met.k_reg': 'Registered candidacies', 'met.k_reg_det': 'president, governor, senator and deputies',
  'met.k_censo': 'In the downloadable census', 'met.k_censo_det': '{p} of candidacies',
  'met.cargo': 'Coverage by office', 'met.cargo_leg': 'Share of TSE-registered candidacies that are in the census. Next to each group, the number of candidacies.',
  'met.genero': 'Coverage by gender', 'met.genero_leg': 'Share of candidacies in the census.',
  'met.raca': 'Coverage by race/colour', 'met.raca_leg': 'Self-reported to TSE; groups with 10 or more candidacies.',
  metodo: [
    ['What this dashboard is', 'An aggregated, descriptive picture of the Instagram activity of candidates, parties and news outlets in the 2026 campaign, updated with each new data collection. This is phase 0: counts, medians and dictionaries. Later phases add model-based labels validated against a human-coded sample.'],
    ['Where the data come from', [
      'Posts: Meta Content Library, CSV export of downloadable accounts (25,000 followers or a verification badge) of candidates, parties and 130 news outlets, checked against TSE records.',
      'Each publication week is downloaded 7 days after it ends (base observation). Since 22 Sep, there is also a same-day capture at 8:30 pm Brasília time.',
      'Public conversation: keyword searches for accounts outside the census (queries G1 to G4).',
      'Ads: Meta Ad Library, by keyword search.',
      'Candidacies, blocs and coalitions: public TSE files (14 Sep 2026).']],
    ['How to read it', [
      "Bloc is the presidential coalition of the candidate's party: an electoral alliance, not ideology.",
      'Days are in UTC, as in the Content Library filters; Brasília is UTC−3.',
      'Medians and quartiles are shown only with 10 or more posts; below that, "—".',
      'Topics and mentions are dictionary counts, with no model and no validation.']],
    ['Caveats', [
      'The census is not a random sample: coverage is lower among women, Black, pardo and Indigenous candidates, non-incumbents and candidates from the North (charts above).',
      'Engagement depends on post age at observation; compare within the same week.',
      "About 9% of posts hide their like counts; each median's denominator is the number of posts with that metric.",
      'The observation measures what survived until collection, not everything that was published.',
      'Nothing here is causal.']],
    ['What is not here', 'Post text, post identifiers, links and media, Meta internal identifiers, and any per-account data for the public conversation line. Raw data stay with the researchers approved for the project.'],
    ['Terms of use', [
      'Restricted to the project group; do not share the password.',
      'Nothing is made public before the certification of elected candidates (diplomação) on 18 Dec 2026.',
      'When citing, credit the Meta Content Library and the Ad Library as sources, and TSE for candidacy data.']],
    ['Next phases', [
      'Sentiment, incivility and discourse function (acclaim, attack, defence) by model, with human validation.',
      'Who talks about whom, with the stance (favourable, unfavourable, neutral) of each mention.',
      'Topics per profile and emerging topics.',
      'Engagement models with account fixed effects (rate ratios and odds ratios).']],
  ],
},
};
