/* BRPOL 2026 — textos do painel em português e inglês. Chave ausente em inglês cai no português.
   {nome} é substituído pelo valor correspondente. Nas explicações (ajuda.*), uma linha em branco separa parágrafos. */
window.BRPOL_TEXTOS = {
pt: {
  'lingua.outra': 'English', 'lingua.dica': 'Mudar o idioma para inglês',
  'titulo.app': 'BRPOL 2026 · Instagram na campanha',
  'bloqueio.desc': 'Painel restrito do projeto BRPOL (UFRJ × NUS): Instagram na campanha eleitoral de 2026, com dados agregados.',
  'bloqueio.senha': 'Senha do painel', 'bloqueio.lembrar': 'Lembrar neste navegador',
  'bloqueio.abrir': 'Abrir', 'bloqueio.abrindo': 'Abrindo…',
  'bloqueio.embargo': 'Os resultados são preliminares e não podem ser divulgados antes da diplomação, em 18 de dezembro de 2026.',
  'erro.senha': 'Senha incorreta.', 'erro.abrir': 'Não foi possível abrir os dados ({msg}).',
  'erro.sem_arquivo': 'Arquivo de dados não encontrado.', 'erro.invalido': 'Arquivo de dados inválido.',
  'erro.iniciar': 'Erro ao iniciar: {msg}',
  'tema.auto': 'Tema: automático', 'tema.dark': 'Tema: escuro', 'tema.light': 'Tema: claro', 'tema.dica': 'Alternar tema claro/escuro',
  'sair': 'Sair', 'sair.dica': 'Esquecer a senha neste navegador',
  'rodape': 'Fontes: Meta Content Library (posts do Instagram), Meta Ad Library (anúncios) e TSE (candidaturas). Painel restrito aos pesquisadores do projeto; resultados preliminares, não divulgar antes de 18/12/2026.',
  'sub': 'Atualizado em {data} · posts de {de} a {ate} · fase {fase}',
  'fase.0': '0 — descritiva',
  'ver_tabela': 'Ver tabela', 'ocultar_tabela': 'Ocultar tabela',
  'setas': 'Use as setas para percorrer os valores',
  'ajuda.botao': 'Como ler este gráfico',
  'semana_de': 'Semana {s}', 'todas_semanas': 'Todas as semanas',
  'intervalo': '{a} a {b}', 'e': ' e ', 'menos10': 'Menos de 10 posts.',
  'posts': 'Posts', 'contas': 'Contas', 'dia': 'Dia', 'semana': 'Semana', 'todos': 'Todos', 'todas': 'Todas',
  'mediana': 'Mediana', 'parcela': 'Parcela', 'cargo': 'Cargo', 'uf': 'UF', 'campo': 'Campo', 'partido': 'Partido',
  'brasil': 'Brasil',

  'aba.geral': 'Visão geral', 'aba.perfis': 'Perfis', 'aba.engajamento': 'Engajamento', 'aba.temas': 'Temas e menções',
  'aba.conversa': 'Conversa pública', 'aba.anuncios': 'Anúncios', 'aba.metodo': 'Cobertura e método',

  'seg.lula': 'Coligação de Lula', 'seg.lula.curto': 'Lula',
  'seg.pl': 'Coligação do PL', 'seg.pl.curto': 'PL',
  'seg.outra_presidencial': 'Outras candidaturas presidenciais', 'seg.outra_presidencial.curto': 'Outras presid.',
  'seg.sem_presidencial': 'Partidos sem candidato a presidente', 'seg.sem_presidencial.curto': 'Sem presid.',
  'seg.partido': 'Contas de partidos', 'seg.partido.curto': 'Partidos',
  'seg.veiculo': 'Veículos de notícia', 'seg.veiculo.curto': 'Veículos',
  'seg.sem_casamento': 'Sem casamento com o TSE', 'seg.sem_casamento.curto': 'Sem casamento',
  'seg.sem_campo': 'Candidatos sem campo', 'seg.sem_campo.curto': 'Sem campo',
  'seg.governo': 'Governos e órgãos públicos', 'seg.governo.curto': 'Governo',
  'seg.outros': 'Outros anunciantes', 'seg.outros.curto': 'Outros',
  'seg.candidatos': 'Candidatos', 'seg.candidatos.curto': 'Candidatos',

  'cargo.todos': 'Todos os cargos', 'cargo.presidente': 'Presidente', 'cargo.governador': 'Governador',
  'cargo.senador': 'Senador', 'cargo.dep_federal': 'Deputado federal', 'cargo.dep_estadual': 'Deputado estadual ou distrital',
  'cargo.outro': 'Outro cargo', 'cargo.sem_cargo': 'Sem cargo no "pago por"',
  'tse.DEPUTADO ESTADUAL': 'Deputado estadual', 'tse.DEPUTADO FEDERAL': 'Deputado federal', 'tse.DEPUTADO DISTRITAL': 'Deputado distrital',
  'tse.SENADOR': 'Senador', 'tse.GOVERNADOR': 'Governador', 'tse.PRESIDENTE': 'Presidente',
  'tse.MASCULINO': 'Masculino', 'tse.FEMININO': 'Feminino', 'tse.BRANCA': 'Branca', 'tse.PARDA': 'Parda', 'tse.PRETA': 'Preta',
  'tse.INDÍGENA': 'Indígena', 'tse.AMARELA': 'Amarela', 'tse.NÃO INFORMADO': 'Não informado', 'tse.NÃO DIVULGÁVEL': 'Não divulgável',

  'metrica.curtidas': 'Curtidas', 'metrica.comentarios': 'Comentários', 'metrica.views': 'Visualizações',
  'formato.video': 'Vídeo', 'formato.foto': 'Foto', 'formato.carrossel': 'Carrossel', 'formato.story': 'Story', 'formato.outro': 'Outro',
  'grupo.todos': 'Todos', 'grupo.candidato': 'Candidatos', 'grupo.partido': 'Partidos',
  'grupo.veiculo_nacional': 'Veículos nacionais', 'grupo.veiculo_regional': 'Veículos regionais',
  'grupo1.candidato': 'Candidato', 'grupo1.partido': 'Partido', 'grupo1.veiculo_nacional': 'Veículo nacional', 'grupo1.veiculo_regional': 'Veículo regional',
  'lado.extrema_esquerda': 'extrema-esquerda', 'lado.esquerda': 'esquerda', 'lado.centro_esquerda': 'centro-esquerda',
  'lado.centro': 'centro', 'lado.centro_direita': 'centro-direita', 'lado.direita': 'direita', 'lado.extrema_direita': 'extrema-direita',
  'lado.sem_classificacao': 'sem classificação',
  'tipo_conta.creator': 'Criador de conteúdo', 'tipo_conta.business': 'Empresa ou organização', 'tipo_conta.personal': 'Pessoal',
  'tipo_ad.candidatura': 'Candidatura', 'tipo_ad.partido': 'Partido', 'tipo_ad.governo': 'Governo', 'tipo_ad.outros': 'Outros',

  'tema.religiao': 'Religião', 'tema.familia': 'Família', 'tema.costumes': 'Costumes',
  'tema.seguranca': 'Segurança pública', 'tema.economia': 'Economia e empreendedorismo', 'tema.trabalho': 'Trabalho e emprego',
  'tema.saude': 'Saúde', 'tema.educacao': 'Educação', 'tema.direitos': 'Direitos e previdência', 'tema.agro': 'Agronegócio',
  'tema.meio_ambiente': 'Meio ambiente', 'tema.cultura': 'Cultura e esporte', 'tema.politica_externa': 'Política externa',
  'tema.corrupcao': 'Corrupção e instituições',
  'alvo.bolsonaro': 'Bolsonaro (qualquer)',
  'publico.female': 'Mulheres', 'publico.male': 'Homens', 'publico.unknown': 'Não informado',
  'regiao.fora do Brasil': 'Fora do Brasil', 'regiao.desconhecida': 'Desconhecida',

  'marco.propaganda': 'propaganda', 'marco.hgpe': 'horário eleitoral', 'marco.turno1': '1º turno', 'marco.turno2': '2º turno',
  'banda.sem': 'sem coleta',

  'geral.k_posts': 'Posts no censo', 'geral.k_posts_det': 'únicos, de contas conferidas',
  'geral.k_contas_det': '{c} candidatos · {p} partidos · {v} veículos',
  'geral.k_dias': 'Dias com coleta', 'geral.k_dias_det': 'de {n}, de {de} a {ate}', 'geral.k_semanas': 'Semanas',
  'geral.aviso_sem': 'Sem dados de {faixas}: essa semana ainda não foi baixada.',
  'geral.g1': 'Posts por dia das contas de candidatos, por campo',
  'geral.g1_leg': 'Campo é a coligação presidencial do partido do candidato (dados do TSE). Dia UTC da publicação.',
  'geral.g2': 'Posts por dia dos veículos de notícia', 'geral.g2_leg': 'Veículos nacionais e regionais do censo.',
  'geral.g3': 'Contas de candidatos que publicaram no dia', 'geral.g3_leg': 'Quantas contas de candidatos do censo tiveram ao menos um post.',
  'geral.ativas': 'Contas ativas',
  'geral.semanas': 'Semanas de publicação',
  'geral.semanas_leg': 'Semanas de domingo a sábado; a primeira começa no sábado 15/08, linha de base antes da propaganda.',

  'perfis.busca': 'Buscar', 'perfis.busca_ph': 'Nome ou usuário', 'perfis.busca_aria': 'Buscar conta',
  'perfis.tipo': 'Tipo de conta', 'perfis.ordenar': 'Ordenar por', 'perfis.nome': 'Nome',
  'perfis.ord_curtidas': 'Mediana de curtidas', 'perfis.ord_comentarios': 'Mediana de comentários', 'perfis.ord_views': 'Mediana de visualizações',
  'perfis.card': 'Contas do censo',
  'perfis.card_leg': 'Clique numa conta para ver a ficha. Medianas por post, com 10 posts ou mais; stories ficam fora.',
  'perfis.col_conta': 'Conta', 'perfis.col_cargo': 'Cargo · UF', 'perfis.col_semana': 'Por semana',
  'perfis.contagem': '{n} de {total} contas', 'perfis.mais': 'Mostrar mais 50',
  'perfis.mesmo_cargo': 'mesmo cargo', 'perfis.mesmo_campo': 'mesmo campo',
  'perfis.pares': 'pares: {v}', 'perfis.pares_x': 'pares: {v} · {x}× a mediana',
  'perfis.fechar': 'Fechar', 'perfis.dias_post': '{n} dias com post',
  'perfis.pares_nota': 'Pares: {n} contas ({desc}).',
  'perfis.por_semana': 'Posts por semana de publicação', 'perfis.formatos': 'Formatos',
  'perfis.temas': 'Temas: parcela dos posts que cita cada tema',
  'perfis.esta': 'Esta conta', 'perfis.med_pares': 'Mediana dos pares',
  'perfis.temas_nota': 'Traço vertical: mediana dos pares.',
  'perfis.hashtags': 'Hashtags mais usadas (3 posts ou mais)',

  'eng.metrica': 'Métrica', 'eng.semanas': 'Semanas de publicação', 'eng.todo': 'Todo o período',
  'eng.periodo_todo': 'todo o período', 'eng.periodo_n': '{n} semanas', 'eng.periodo_1': 'semana {s}',
  'eng.idade_sel': 'Posts vistos de {a} a {b} dias depois de publicados.', 'eng.idade_sel1': 'Posts vistos cerca de {a} dias depois de publicados.',
  'eng.quartis': '1º a 3º quartil',
  'eng.g1': 'Mediana de {m} por post · {p}',
  'eng.g1_leg': 'Candidatos, {cargo}. A barra é a mediana; o traço fino vai do 1º ao 3º quartil.',
  'eng.g1_nota': 'Partidos e veículos de notícia, que têm outra escala, estão na tabela.',
  'eng.segmento': 'Segmento', 'eng.q1': '1º quartil', 'eng.q3': '3º quartil',
  'eng.g2': 'Mediana de {m} por formato · {p}', 'eng.g2_leg': 'Candidatos, {cargo}.',
  'eng.g2_nota': 'Partidos e veículos na tabela.', 'eng.formato': 'Formato',
  'eng.g4': 'Horário das publicações (Brasília)',
  'eng.g4_leg': 'Parcela dos posts de cada campo publicada em cada hora do dia, todas as semanas e cargos.', 'eng.hora': 'Hora',
  'eng.g5': 'Quanto das curtidas da semana já existia no primeiro dia',
  'eng.g5_leg': 'Posts vistos duas vezes: na captura do dia em que saíram e na semanal. A barra é a mediana da razão entre as duas contagens.',
  'eng.faixa_captura': 'Idade na captura do dia', 'eng.razao': 'Razão (dia ÷ semanal)',

  'temas.alvo': 'Menção ao longo do tempo', 'temas.hashtags_de': 'Hashtags de',
  'temas.aviso': 'Temas e menções são contagens de palavras (dicionário do painel, ainda em revisão), sem modelo: um post que cita um tema pode falar dele de passagem.',
  'temas.citam': 'Posts que citam', 'temas.no_seg': 'Posts no segmento',
  'temas.mapa_temas': 'Temas · {s}', 'temas.mapa_temas_leg': 'Parcela dos posts de cada segmento que cita cada tema.',
  'temas.mapa_alvos': 'Menções · {s}', 'temas.mapa_alvos_leg': 'Parcela dos posts de cada segmento que cita cada nome.',
  'temas.linha': 'Posts que citam {a}, por semana', 'temas.linha_leg': 'Parcela dos posts de cada segmento.',
  'temas.linha_nota': 'Veículos de notícia em cinza escuro.',
  'temas.tags': 'Hashtags · {seg}', 'temas.tags_leg': '{s}. Hashtags com 10 posts ou mais, de 3 contas ou mais.',
  'temas.tags_vazio': 'Nenhuma hashtag passa do mínimo nesse recorte.',

  'conv.vazio': 'A linha de conversa ainda não foi consolidada.',
  'conv.k_posts': 'Posts na base', 'conv.k_posts_det': 'fora do censo, sem descartes',
  'conv.k_contas': 'Contas por semana', 'conv.k_contas_det': 'mediana de contas distintas',
  'conv.aviso': 'Posts sobre a eleição de contas fora do censo, achados por palavras-chave. Tudo aqui é agregado; nada é mostrado por conta.',
  'conv.g1': 'Posts por dia na conversa pública', 'conv.g1_leg': 'Um post conta uma vez, mesmo que tenha casado com mais de uma busca.',
  'conv.mencoes': 'Quem domina a conversa', 'conv.mencoes_leg': 'Parcela diária dos posts da conversa que cita cada nome. Todos os gráficos na mesma escala.',
  'conv.media': 'média: {v}',
  'conv.agenda': 'Agenda do público × agenda dos candidatos · {s}',
  'conv.agenda_leg': 'Parcela dos posts que cita cada tema, na conversa pública e nos posts dos candidatos da mesma semana.',
  'conv.publico': 'Conversa pública', 'conv.candidatos': 'Candidatos',
  'conv.alta': 'Hashtags que mais cresceram · {s}', 'conv.alta_leg': 'Posts na semana e variação em relação à semana anterior. Com 20 posts ou mais, de 5 contas ou mais.',
  'conv.mais_usadas': 'Hashtags mais usadas · {s}',
  'conv.nova': 'nova', 'conv.var': 'Variação', 'conv.ant': 'Semana anterior',
  'conv.quem': 'Quem posta · {s}', 'conv.quem_leg': 'Tipo de conta, como o Instagram classifica, e formato do post.',

  'ads.rel_titulo': 'Gasto em anúncios políticos na Meta',
  'ads.rel_aviso': 'Relatório da Biblioteca de Anúncios da Meta: {janela} até {d}, incluindo a pré-campanha. Páginas que gastaram menos de R$ 100 ficam fora dos totais.',
  'janela.last_90_days': '90 dias', 'janela.last_30_days': '30 dias', 'janela.last_7_days': '7 dias', 'janela.lifelong': 'todo o período', 'janela.yesterday': '1 dia',
  'ads.k_total': 'Gasto total', 'ads.k_total_det': '{n} páginas com R$ 100 ou mais',
  'ads.k_cand': 'Gasto de candidaturas', 'ads.k_cand_det': '{p} do total',
  'ads.k_n': 'Candidaturas que anunciaram', 'ads.k_n_det': 'de {n} registradas',
  'ads.k_gov': 'Governos e órgãos públicos', 'ads.k_gov_det': '{p} do total',
  'ads.local': 'Estado', 'ads.disputa_cargo': 'Disputa',
  'ads.g_uf': 'Gasto por estado', 'ads.g_uf_leg': 'Onde os anúncios foram vistos, todos os anunciantes.',
  'ads.g_tipo': 'Quem anuncia · {uf}', 'ads.g_tipo_leg': 'Gasto por grupo de anunciante. Candidaturas e partidos pelo campo.',
  'ads.g_top': 'Maiores anunciantes · {uf}', 'ads.g_top_leg': 'As páginas que mais gastaram com anúncios vistos em {uf}.',
  'ads.g_cargo': 'Gasto das candidaturas por cargo e campo', 'ads.g_cargo_leg': 'Brasil. Soma das páginas ligadas a cada candidatura.',
  'ads.g_disputa': 'A disputa: {cargo} · {uf}', 'ads.g_disputa_leg': '{a} de {n} candidaturas anunciaram. Gasto de todas as páginas ligadas a cada candidatura, no Brasil.',
  'ads.g_disputa_prop': 'As 20 candidaturas que mais gastaram. {a} de {n} candidaturas anunciaram.',
  'ads.nao_anunciou': 'não anunciou', 'ads.menos100': 'menos de R$ 100',
  'ads.destaques': 'Destaques', 'ads.destaques_leg': 'Gerados a partir dos números acima; descritivos, sem interpretação.',
  'ads.d1': '{nome} ({cargo}, {partido}) é a candidatura que mais gastou: {v}, {p} do gasto de todas as candidaturas.',
  'ads.d2': 'Candidaturas respondem por {p1} do gasto em anúncios políticos; governos e órgãos públicos, por {p2}.',
  'ads.d3': 'Entre as candidaturas, o grupo que mais gastou foi {campo}: {v} ({p}).',
  'ads.d4': '{uf} concentra {p} do gasto total, a maior parcela entre os estados.',
  'ads.d5': 'Em {uf}, o maior anunciante é {nome} ({tipo}), com {v}.',
  'ads.d6': 'Na disputa de {cargo} em {uf}, {a} de {n} candidaturas anunciaram; {nome} concentra {p} do gasto.',
  'ads.anuncios': 'Anúncios', 'ads.gasto_curto': 'Gasto', 'ads.impressoes': 'Impressões', 'ads.citam_lula': 'Citam Lula',
  'ads.pagina': 'Página', 'ads.n_anuncios': '{n} anúncios', 'ads.n_paginas': '{n} páginas', 'ads.n_cand': '{n} candidaturas', 'ads.n_cand1': '1 candidatura',
  'ads.citam': 'Citam "{b}" no texto', 'ads.vazio': 'Nenhum dado de anúncios consolidado ainda.',
  'ads.busca_titulo': 'Anúncios que citam "{b}" (busca por palavra-chave)',
  'ads.busca_aviso': 'Anúncios que a busca por "{b}" retornou (baixados em {d}), com início de veiculação a partir de {ini}. Gasto e impressões vêm em faixas: a barra cheia vai até o piso e a parte clara até o teto.',
  'ads.b_quem': 'Quem usa o nome de Lula nos anúncios', 'ads.b_quem_leg': 'Parcela dos anúncios de cada campo com "Lula" no texto.',
  'ads.b_dia': 'Anúncios iniciados por dia, por campo', 'ads.b_dia_leg': 'Dia de início da veiculação. Anúncios sem casamento com o TSE ficam fora.',
  'ads.publico_de': 'Público de', 'ads.todos': 'Todos os anúncios',
  'ads.b_publico': 'Quem viu: idade e gênero', 'ads.b_publico_leg': 'Parcela das impressões (ponto médio da faixa de cada anúncio).',
  'ads.b_regiao': 'Onde foi visto', 'ads.b_regiao_leg': 'Parcela das impressões por UF.',

  'met.nota': 'Barra: candidaturas com conta no censo. Traço: declararam Instagram ao TSE.',
  'met.registradas': 'Registradas', 'met.declarado': 'Instagram declarado', 'met.no_censo': 'No censo', 'met.grupo': 'Grupo',
  'met.k_reg': 'Candidaturas registradas', 'met.k_reg_det': 'presidente, governador, senador e deputados',
  'met.k_censo': 'No censo baixável', 'met.k_censo_det': '{p} das candidaturas',
  'met.cargo': 'Cobertura por cargo', 'met.cargo_leg': 'Parcela das candidaturas registradas no TSE que está no censo. Ao lado de cada grupo, o número de candidaturas.',
  'met.genero': 'Cobertura por gênero', 'met.genero_leg': 'Parcela das candidaturas no censo.',
  'met.raca': 'Cobertura por cor ou raça', 'met.raca_leg': 'Autodeclaração ao TSE; grupos com 10 candidaturas ou mais.',

  // ---- explicações dos botões "?"
  'ajuda.geral_posts': 'Cada linha soma os posts publicados no dia pelas contas de candidatos de um campo. Campo é a coligação presidencial do partido do candidato, tirada do registro no TSE: aliança eleitoral, não ideologia.\n\nO dia é o dia UTC, como no filtro da Content Library. Brasília é UTC−3, então um post das 22h de Brasília cai no dia seguinte.\n\nAs faixas cinza marcam dias sem coleta: a semana ainda não foi baixada. Os dias mais recentes vêm da captura feita às 20h30 de Brasília do próprio dia; posts publicados entre 20h30 e 21h entram quando a semana é baixada completa.',
  'ajuda.geral_veiculos': 'Posts por dia das 130 contas de veículos de notícia do censo, nacionais e regionais. A queda nos fins de semana é da rotina das redações.',
  'ajuda.geral_ativas': 'Quantas contas de candidatos do censo publicaram ao menos um post no dia. Mostra se o aumento de posts vem de mais contas ativas ou de mais posts por conta.',
  'ajuda.geral_semanas': 'Semanas de publicação vão de domingo a sábado. A primeira vai do sábado 15/08 (linha de base, véspera da propaganda) até 22/08.\n\nCada semana é baixada da Content Library depois de terminar. As três primeiras foram baixadas mais tarde, com os posts já com 15 a 29 dias; a partir de 06/09, os posts são vistos com 7 a 14 dias. Isso importa para o engajamento, não para a contagem de posts.',
  'ajuda.perfis': 'Uma linha por conta do censo: candidatos com 25 mil seguidores ou selo de verificação, contas de partidos e veículos de notícia.\n\nAs medianas usam os posts vistos na coleta semanal, de 7 a 32 dias depois de publicados, e só aparecem com 10 posts ou mais. Stories ficam fora, porque não têm curtidas nem comentários.\n\nNa ficha, pares são as contas do mesmo cargo e campo (ou do mesmo tipo, para veículos e partidos). "2× a mediana" quer dizer o dobro da mediana dos pares. Os temas vêm do dicionário do painel.',
  'ajuda.eng_mediana': 'A mediana é o valor do meio: metade dos posts tem mais e metade tem menos. O traço fino vai do 1º quartil (25% dos posts abaixo) ao 3º (75% abaixo). A mediana não se deixa puxar por um ou outro post que viralizou.\n\nIdade na observação: curtidas e comentários continuam crescendo depois que o post sai. Cada semana foi vista numa idade: as três primeiras com 15 a 29 dias, as seguintes com 7 a 14. Ao juntar semanas, misturam-se idades; compare campos dentro da mesma seleção, não semanas entre si.\n\nPara permitir qualquer combinação de semanas, o painel guarda a distribuição de cada semana em faixas estreitas e calcula a mediana da soma; o erro é menor que 2%. Só entram grupos com 10 posts ou mais.',
  'ajuda.eng_formato': 'A mesma mediana, separada pelo formato do post: vídeo (inclui reels), foto e carrossel (álbum com várias imagens). Stories ficam fora, porque não têm curtidas nem comentários.',
  'ajuda.eng_horario': 'Para cada campo, a parcela dos posts publicada em cada hora do dia, no horário de Brasília. As curvas somam 100% cada uma. Mostra a rotina de publicação, não o engajamento.',
  'ajuda.eng_duas': 'Alguns posts foram vistos duas vezes: na captura das 20h30 do dia em que saíram (com 0 a 24 horas) e depois na coleta semanal (com 7 a 14 dias). A razão entre as duas contagens diz quanto do engajamento da semana já existia no primeiro dia: 0,6 quer dizer 60%.\n\nNão é uma curva de crescimento hora a hora; são só dois pontos de cada post. Posts que sumiram entre as duas coletas não entram.',
  'ajuda.temas_mapa': 'Cada célula é a parcela dos posts do segmento que cita ao menos uma palavra do tema, no texto da legenda. Um post pode citar vários temas.\n\nO dicionário é do painel (config/temas_painel.yaml), inspirado nas macrocategorias do NetLab UFRJ, e ainda está em revisão. É contagem de palavras: não diz se o post defende ou ataca, nem se o tema é central. Texto dentro de imagens e vídeos não entra.',
  'ajuda.temas_mencoes': 'Parcela dos posts que cita cada nome ou perfil. "Bolsonaro (qualquer)" conta qualquer Bolsonaro: Jair, Flávio, Eduardo, Michelle. "STF / Moraes" junta STF, Supremo e Moraes. Citar não quer dizer apoiar: a postura de cada menção entra na próxima fase.',
  'ajuda.temas_linha': 'A mesma parcela de posts que cita o nome escolhido, semana a semana, para cada campo e para os veículos de notícia. A última semana ainda está incompleta até a coleta semanal.',
  'ajuda.temas_tags': 'Hashtags mais usadas pelas contas do segmento no período escolhido. Só entram hashtags com 10 posts ou mais, de 3 contas ou mais.',
  'ajuda.conv_total': 'A conversa pública são posts sobre a eleição de contas que não estão no censo, achados por palavras-chave em quatro buscas: nomes dos presidenciáveis e do STF; rótulos políticos (petista, bolsonarista); eleição e voto (TSE, urnas, pesquisas); e candidaturas.\n\nPosts de contas do censo e falsos positivos (lula, o molusco; urna funerária) ficam de fora. Cada semana é baixada 7 dias depois de terminar.',
  'ajuda.conv_mencoes': 'Um gráfico por nome, todos na mesma escala: a parcela dos posts de cada dia que cita aquele nome.\n\nComo a própria busca usa esses nomes, o volume total é consequência da busca. O que vale é a comparação entre nomes e ao longo do tempo.',
  'ajuda.conv_agenda': 'Para cada tema, a barra de cima é a parcela dos posts da conversa pública que cita o tema; a de baixo, a parcela dos posts dos candidatos na mesma semana. Mostra o que o público discute mais, ou menos, que os candidatos.\n\nA conversa foi achada por palavras sobre a eleição, então tende a falar mais de política e instituições.',
  'ajuda.conv_alta': 'As hashtags mais usadas na semana e quanto cada uma mudou em relação à semana anterior. "Nova" é hashtag que não aparecia na semana anterior. Só entram hashtags com 20 posts ou mais, de 5 contas ou mais.',
  'ajuda.conv_quem': 'O Instagram classifica as contas em criador de conteúdo, empresa ou organização, e pessoal. O formato é o do post: vídeo, foto, carrossel ou story.',
  'ajuda.ads_uf': 'Do relatório público da Biblioteca de Anúncios da Meta: quanto se gastou em anúncios sobre política e eleições vistos em cada estado, por qualquer anunciante (candidatos, partidos, governos, empresas, organizações).\n\nO estado é onde o anúncio foi visto, não onde o anunciante está. O período são os 90 dias até a data do relatório, então inclui a pré-campanha. A Meta não detalha páginas que gastaram menos de R$ 100.',
  'ajuda.ads_tipo': 'Cada página foi classificada: candidatura (ligada a uma candidatura do TSE pelo CNPJ de campanha no "pago por", pelo nome da página ou pelos anúncios), partido (o nome da página é de um partido), governo (governos, prefeituras, ministérios, legislativo, judiciário, órgãos e empresas públicas) e outros (empresas, institutos, veículos, perfis sem candidatura casada).\n\nCandidaturas e partidos aparecem pela cor do campo. O gasto é da página, quem quer que tenha pago: pessoa, partido ou campanha.',
  'ajuda.ads_top': 'As dez páginas que mais gastaram com anúncios vistos no estado escolhido (no Brasil, as quinze maiores). A cor é o campo, para candidaturas e partidos; cinza para governo e outros.',
  'ajuda.ads_cargo': 'Soma do gasto das páginas ligadas a candidaturas, por cargo e campo, no Brasil inteiro e nos 90 dias do relatório.',
  'ajuda.ads_disputa': 'Todas as candidaturas registradas no TSE para o cargo e o estado escolhidos, com o gasto das páginas ligadas a cada uma (no Brasil inteiro). Candidaturas sem anúncios aparecem com "não anunciou". Para deputados, as 20 que mais gastaram.\n\nA ligação entre página e candidatura é automática e pode errar: páginas com nome diferente do nome de urna podem ficar de fora, e homônimos no mesmo estado podem ser confundidos.',
  'ajuda.ads_destaques': 'Frases geradas a partir dos números do relatório, sem interpretação. Mudam com o estado e a disputa escolhidos.',
  'ajuda.busca': 'Anúncios individuais que a busca por palavra-chave na Biblioteca retornou, com faixas de gasto e impressões, público por idade e gênero e distribuição por estado. É uma amostra: só entram anúncios que citam o termo (no texto ou em outro campo).',
  'ajuda.met_cobertura': 'Registradas: candidaturas titulares no TSE (presidente, governador, senador e deputados). Instagram declarado: informaram um perfil ao TSE ou o perfil foi achado por busca. No censo: a conta pode ser baixada da Content Library (25 mil seguidores ou selo de verificação) e publicou na semana da varredura.\n\nA diferença entre grupos mostra quem fica menos visível nos dados.',

  metodo: [
    ['O que é este painel', 'Um retrato agregado e descritivo do Instagram das candidaturas, partidos e veículos de notícia na campanha de 2026, atualizado a cada nova coleta. Esta é a fase 0: contagens, medianas e dicionários. As fases seguintes acrescentam rótulos por modelo, validados por amostra humana.'],
    ['De onde vêm os dados', [
      'Posts: Meta Content Library, exportação em CSV das contas baixáveis (25 mil seguidores ou selo de verificação) de candidatos, partidos e 130 veículos, conferidas contra o TSE.',
      'Cada semana de publicação é baixada depois de terminar; os dias mais recentes vêm de uma captura diária às 20h30 de Brasília, substituída pela semanal quando ela chega.',
      'Conversa pública: buscas por palavra-chave de contas fora do censo.',
      'Anúncios: relatório público da Biblioteca de Anúncios da Meta (gasto por anunciante e por estado) e buscas por palavra-chave (anúncios individuais).',
      'Candidaturas, campo e coligações: arquivos públicos do TSE (14/09/2026).']],
    ['Como ler', [
      'Campo é a coligação presidencial do partido do candidato: aliança eleitoral, não ideologia.',
      'Dias em UTC, como nos filtros da Content Library; Brasília é UTC−3.',
      'Medianas e quartis aparecem só com 10 posts ou mais; abaixo disso, "—".',
      'Temas e menções são contagens por dicionário, sem modelo e sem validação.',
      'Os botões "?" ao lado de cada gráfico explicam o cálculo.']],
    ['Ressalvas', [
      'O censo não é amostra aleatória: a cobertura é menor entre mulheres, candidatos pretos, pardos e indígenas, sem mandato e do Norte (gráficos acima).',
      'Engajamento depende da idade do post quando foi visto; compare dentro da mesma seleção de semanas.',
      'Cerca de 9% dos posts escondem as curtidas; o denominador de cada mediana é o número de posts com a métrica.',
      'A coleta mede o que sobreviveu até ser baixado, não tudo o que foi publicado.',
      'Nenhum resultado aqui é causal.']],
    ['O que não está aqui', 'Texto de post, identificador de post, links e mídia, identificadores internos da Meta e qualquer dado por conta na linha de conversa. Os dados brutos ficam só com os pesquisadores aprovados no projeto.'],
    ['Regras de uso', [
      'Painel restrito ao grupo do projeto; não repasse a senha.',
      'Nada é divulgado publicamente antes da diplomação, em 18/12/2026.',
      'Ao citar, indique a Meta Content Library e a Ad Library como fontes e o TSE para as candidaturas.']],
    ['Próximas fases', [
      'Sentimento, incivilidade e função do discurso (aclamação, ataque, defesa) por modelo, com validação humana.',
      'Quem fala de quem, com a postura (favorável, desfavorável, neutra) de cada menção.',
      'Tópicos por perfil e tópicos emergentes; temas por modelo nas mesmas categorias do dicionário.',
      'Modelos de engajamento com efeito fixo de conta (razões de taxas e razões de chances).']],
  ],
},

en: {
  'lingua.outra': 'Português', 'lingua.dica': 'Switch the language to Portuguese',
  'titulo.app': 'BRPOL 2026 · Instagram in the campaign',
  'bloqueio.desc': "Restricted dashboard of the BRPOL project (UFRJ × NUS): Instagram in Brazil's 2026 election campaign, aggregated data.",
  'bloqueio.senha': 'Dashboard password', 'bloqueio.lembrar': 'Remember on this browser',
  'bloqueio.abrir': 'Open', 'bloqueio.abrindo': 'Opening…',
  'bloqueio.embargo': 'Results are preliminary and must not be made public before the certification of elected candidates (diplomação) on 18 December 2026.',
  'erro.senha': 'Wrong password.', 'erro.abrir': 'Could not open the data ({msg}).',
  'erro.sem_arquivo': 'Data file not found.', 'erro.invalido': 'Invalid data file.',
  'erro.iniciar': 'Startup error: {msg}',
  'tema.auto': 'Theme: auto', 'tema.dark': 'Theme: dark', 'tema.light': 'Theme: light', 'tema.dica': 'Toggle light/dark theme',
  'sair': 'Sign out', 'sair.dica': 'Forget the password on this browser',
  'rodape': "Sources: Meta Content Library (Instagram posts), Meta Ad Library (ads) and TSE, Brazil's electoral court (candidacies). Restricted to project researchers; preliminary results, not to be made public before 18 Dec 2026.",
  'sub': 'Updated {data} · posts from {de} to {ate} · phase {fase}',
  'fase.0': '0 — descriptive',
  'ver_tabela': 'Show table', 'ocultar_tabela': 'Hide table',
  'setas': 'Use the arrow keys to move through the values',
  'ajuda.botao': 'How to read this chart',
  'semana_de': 'Week of {s}', 'todas_semanas': 'All weeks',
  'intervalo': '{a}–{b}', 'e': ' and ', 'menos10': 'Fewer than 10 posts.',
  'posts': 'Posts', 'contas': 'Accounts', 'dia': 'Day', 'semana': 'Week', 'todos': 'All', 'todas': 'All',
  'mediana': 'Median', 'parcela': 'Share', 'cargo': 'Office', 'uf': 'State', 'campo': 'Bloc', 'partido': 'Party',
  'brasil': 'Brazil',

  'aba.geral': 'Overview', 'aba.perfis': 'Profiles', 'aba.engajamento': 'Engagement', 'aba.temas': 'Topics and mentions',
  'aba.conversa': 'Public conversation', 'aba.anuncios': 'Ads', 'aba.metodo': 'Coverage and method',

  'seg.lula': "Lula's coalition", 'seg.lula.curto': 'Lula',
  'seg.pl': 'PL coalition', 'seg.pl.curto': 'PL',
  'seg.outra_presidencial': 'Other presidential candidacies', 'seg.outra_presidencial.curto': 'Other pres.',
  'seg.sem_presidencial': 'Parties without a presidential candidate', 'seg.sem_presidencial.curto': 'No pres.',
  'seg.partido': 'Party accounts', 'seg.partido.curto': 'Parties',
  'seg.veiculo': 'News outlets', 'seg.veiculo.curto': 'Outlets',
  'seg.sem_casamento': 'Not matched to TSE', 'seg.sem_casamento.curto': 'Unmatched',
  'seg.sem_campo': 'Candidates without a bloc', 'seg.sem_campo.curto': 'No bloc',
  'seg.governo': 'Governments and public bodies', 'seg.governo.curto': 'Government',
  'seg.outros': 'Other advertisers', 'seg.outros.curto': 'Other',
  'seg.candidatos': 'Candidates', 'seg.candidatos.curto': 'Candidates',

  'cargo.todos': 'All offices', 'cargo.presidente': 'President', 'cargo.governador': 'Governor',
  'cargo.senador': 'Senator', 'cargo.dep_federal': 'Federal deputy', 'cargo.dep_estadual': 'State or district deputy',
  'cargo.outro': 'Other office', 'cargo.sem_cargo': 'No office in "paid for by"',
  'tse.DEPUTADO ESTADUAL': 'State deputy', 'tse.DEPUTADO FEDERAL': 'Federal deputy', 'tse.DEPUTADO DISTRITAL': 'District deputy',
  'tse.SENADOR': 'Senator', 'tse.GOVERNADOR': 'Governor', 'tse.PRESIDENTE': 'President',
  'tse.MASCULINO': 'Male', 'tse.FEMININO': 'Female', 'tse.BRANCA': 'White', 'tse.PARDA': 'Pardo (mixed race)', 'tse.PRETA': 'Black',
  'tse.INDÍGENA': 'Indigenous', 'tse.AMARELA': 'East Asian descent', 'tse.NÃO INFORMADO': 'Not reported', 'tse.NÃO DIVULGÁVEL': 'Not disclosed',

  'metrica.curtidas': 'Likes', 'metrica.comentarios': 'Comments', 'metrica.views': 'Views',
  'formato.video': 'Video', 'formato.foto': 'Photo', 'formato.carrossel': 'Carousel', 'formato.story': 'Story', 'formato.outro': 'Other',
  'grupo.todos': 'All', 'grupo.candidato': 'Candidates', 'grupo.partido': 'Parties',
  'grupo.veiculo_nacional': 'National outlets', 'grupo.veiculo_regional': 'Regional outlets',
  'grupo1.candidato': 'Candidate', 'grupo1.partido': 'Party', 'grupo1.veiculo_nacional': 'National outlet', 'grupo1.veiculo_regional': 'Regional outlet',
  'lado.extrema_esquerda': 'far left', 'lado.esquerda': 'left', 'lado.centro_esquerda': 'centre-left',
  'lado.centro': 'centre', 'lado.centro_direita': 'centre-right', 'lado.direita': 'right', 'lado.extrema_direita': 'far right',
  'lado.sem_classificacao': 'unclassified',
  'tipo_conta.creator': 'Content creator', 'tipo_conta.business': 'Business or organisation', 'tipo_conta.personal': 'Personal',
  'tipo_ad.candidatura': 'Candidacy', 'tipo_ad.partido': 'Party', 'tipo_ad.governo': 'Government', 'tipo_ad.outros': 'Other',

  'tema.religiao': 'Religion', 'tema.familia': 'Family', 'tema.costumes': 'Social issues (abortion, gender, drugs)',
  'tema.seguranca': 'Public security', 'tema.economia': 'Economy and entrepreneurship', 'tema.trabalho': 'Work and jobs',
  'tema.saude': 'Health', 'tema.educacao': 'Education', 'tema.direitos': 'Rights and pensions', 'tema.agro': 'Agribusiness',
  'tema.meio_ambiente': 'Environment', 'tema.cultura': 'Culture and sport', 'tema.politica_externa': 'Foreign policy',
  'tema.corrupcao': 'Corruption and institutions',
  'alvo.bolsonaro': 'Bolsonaro (any)',
  'publico.female': 'Women', 'publico.male': 'Men', 'publico.unknown': 'Unknown',
  'regiao.fora do Brasil': 'Outside Brazil', 'regiao.desconhecida': 'Unknown',

  'marco.propaganda': 'campaigning', 'marco.hgpe': 'free TV airtime', 'marco.turno1': '1st round', 'marco.turno2': 'runoff',
  'banda.sem': 'no data',

  'geral.k_posts': 'Posts in the census', 'geral.k_posts_det': 'unique, from verified accounts',
  'geral.k_contas_det': '{c} candidates · {p} parties · {v} outlets',
  'geral.k_dias': 'Days with data', 'geral.k_dias_det': 'of {n}, {de} to {ate}', 'geral.k_semanas': 'Weeks',
  'geral.aviso_sem': 'No data for {faixas}: that week has not been downloaded yet.',
  'geral.g1': 'Daily posts by candidate accounts, by bloc',
  'geral.g1_leg': "Bloc is the presidential coalition of the candidate's party (TSE data). UTC day of publication.",
  'geral.g2': 'Daily posts by news outlets', 'geral.g2_leg': 'National and regional outlets in the census.',
  'geral.g3': 'Candidate accounts that posted each day', 'geral.g3_leg': 'Number of candidate accounts in the census with at least one post.',
  'geral.ativas': 'Active accounts',
  'geral.semanas': 'Publication weeks',
  'geral.semanas_leg': 'Weeks run Sunday to Saturday; the first starts on Saturday 15 Aug, a baseline day before campaigning began.',

  'perfis.busca': 'Search', 'perfis.busca_ph': 'Name or username', 'perfis.busca_aria': 'Search account',
  'perfis.tipo': 'Account type', 'perfis.ordenar': 'Sort by', 'perfis.nome': 'Name',
  'perfis.ord_curtidas': 'Median likes', 'perfis.ord_comentarios': 'Median comments', 'perfis.ord_views': 'Median views',
  'perfis.card': 'Census accounts',
  'perfis.card_leg': 'Click an account to see its profile. Per-post medians, with 10 or more posts; stories excluded.',
  'perfis.col_conta': 'Account', 'perfis.col_cargo': 'Office · State', 'perfis.col_semana': 'Per week',
  'perfis.contagem': '{n} of {total} accounts', 'perfis.mais': 'Show 50 more',
  'perfis.mesmo_cargo': 'same office', 'perfis.mesmo_campo': 'same bloc',
  'perfis.pares': 'peers: {v}', 'perfis.pares_x': 'peers: {v} · {x}× the median',
  'perfis.fechar': 'Close', 'perfis.dias_post': '{n} days with posts',
  'perfis.pares_nota': 'Peers: {n} accounts ({desc}).',
  'perfis.por_semana': 'Posts per publication week', 'perfis.formatos': 'Formats',
  'perfis.temas': 'Topics: share of posts mentioning each topic',
  'perfis.esta': 'This account', 'perfis.med_pares': 'Peer median',
  'perfis.temas_nota': 'Vertical tick: peer median.',
  'perfis.hashtags': 'Most used hashtags (3 or more posts)',

  'eng.metrica': 'Metric', 'eng.semanas': 'Publication weeks', 'eng.todo': 'Whole period',
  'eng.periodo_todo': 'whole period', 'eng.periodo_n': '{n} weeks', 'eng.periodo_1': 'week of {s}',
  'eng.idade_sel': 'Posts observed {a} to {b} days after publication.', 'eng.idade_sel1': 'Posts observed about {a} days after publication.',
  'eng.quartis': '1st to 3rd quartile',
  'eng.g1': 'Median {m} per post · {p}',
  'eng.g1_leg': 'Candidates, {cargo}. The bar is the median; the thin line spans the 1st to 3rd quartile.',
  'eng.g1_nota': 'Parties and news outlets, which are on a different scale, are in the table.',
  'eng.segmento': 'Segment', 'eng.q1': '1st quartile', 'eng.q3': '3rd quartile',
  'eng.g2': 'Median {m} by format · {p}', 'eng.g2_leg': 'Candidates, {cargo}.',
  'eng.g2_nota': 'Parties and outlets in the table.', 'eng.formato': 'Format',
  'eng.g4': 'Posting time (Brasília)',
  'eng.g4_leg': "Share of each bloc's posts published in each hour of the day, all weeks and offices.", 'eng.hora': 'Hour',
  'eng.g5': "How much of the week's likes were already there on day one",
  'eng.g5_leg': 'Posts seen twice: in the same-day capture and in the weekly download. The bar is the median ratio between the two counts.',
  'eng.faixa_captura': 'Age at the same-day capture', 'eng.razao': 'Ratio (day ÷ weekly)',

  'temas.alvo': 'Mention over time', 'temas.hashtags_de': 'Hashtags from',
  'temas.aviso': 'Topics and mentions are word counts (dashboard dictionary, still under review), with no model: a post that mentions a topic may only touch on it.',
  'temas.citam': 'Posts mentioning', 'temas.no_seg': 'Posts in segment',
  'temas.mapa_temas': 'Topics · {s}', 'temas.mapa_temas_leg': "Share of each segment's posts mentioning each topic.",
  'temas.mapa_alvos': 'Mentions · {s}', 'temas.mapa_alvos_leg': "Share of each segment's posts mentioning each name.",
  'temas.linha': 'Posts mentioning {a}, by week', 'temas.linha_leg': "Share of each segment's posts.",
  'temas.linha_nota': 'News outlets in dark grey.',
  'temas.tags': 'Hashtags · {seg}', 'temas.tags_leg': '{s}. Hashtags with 10 or more posts from 3 or more accounts.',
  'temas.tags_vazio': 'No hashtag reaches the minimum in this selection.',

  'conv.vazio': 'The public conversation line has not been consolidated yet.',
  'conv.k_posts': 'Posts in the base', 'conv.k_posts_det': 'outside the census, after exclusions',
  'conv.k_contas': 'Accounts per week', 'conv.k_contas_det': 'median of distinct accounts',
  'conv.aviso': 'Election-related posts from accounts outside the census, found by keyword. Everything here is aggregated; nothing is shown per account.',
  'conv.g1': 'Daily posts in the public conversation', 'conv.g1_leg': 'Each post counts once, even if it matched more than one search.',
  'conv.mencoes': 'Who dominates the conversation', 'conv.mencoes_leg': 'Daily share of conversation posts mentioning each name. All charts share the same scale.',
  'conv.media': 'mean: {v}',
  'conv.agenda': "Public agenda × candidates' agenda · {s}",
  'conv.agenda_leg': "Share of posts mentioning each topic, in the public conversation and in candidates' posts from the same week.",
  'conv.publico': 'Public conversation', 'conv.candidatos': 'Candidates',
  'conv.alta': 'Fastest-growing hashtags · {s}', 'conv.alta_leg': 'Posts in the week and change from the previous week. With 20 or more posts from 5 or more accounts.',
  'conv.mais_usadas': 'Most used hashtags · {s}',
  'conv.nova': 'new', 'conv.var': 'Change', 'conv.ant': 'Previous week',
  'conv.quem': 'Who posts · {s}', 'conv.quem_leg': 'Account type, as Instagram classifies it, and post format.',

  'ads.rel_titulo': 'Political ad spending on Meta',
  'ads.rel_aviso': 'Meta Ad Library report: {janela} to {d}, including the pre-campaign period. Pages that spent less than R$ 100 are left out of the totals.',
  'janela.last_90_days': '90 days', 'janela.last_30_days': '30 days', 'janela.last_7_days': '7 days', 'janela.lifelong': 'all time', 'janela.yesterday': '1 day',
  'ads.k_total': 'Total spend', 'ads.k_total_det': '{n} pages with R$ 100 or more',
  'ads.k_cand': 'Candidacy spend', 'ads.k_cand_det': '{p} of the total',
  'ads.k_n': 'Candidacies that advertised', 'ads.k_n_det': 'of {n} registered',
  'ads.k_gov': 'Governments and public bodies', 'ads.k_gov_det': '{p} of the total',
  'ads.local': 'State', 'ads.disputa_cargo': 'Race',
  'ads.g_uf': 'Spend by state', 'ads.g_uf_leg': 'Where the ads were seen, all advertisers.',
  'ads.g_tipo': 'Who advertises · {uf}', 'ads.g_tipo_leg': 'Spend by advertiser group. Candidacies and parties by bloc.',
  'ads.g_top': 'Top advertisers · {uf}', 'ads.g_top_leg': 'The pages that spent the most on ads seen in {uf}.',
  'ads.g_cargo': 'Candidacy spend by office and bloc', 'ads.g_cargo_leg': 'Brazil. Sum of the pages linked to each candidacy.',
  'ads.g_disputa': 'The race: {cargo} · {uf}', 'ads.g_disputa_leg': '{a} of {n} candidacies advertised. Spend of all pages linked to each candidacy, across Brazil.',
  'ads.g_disputa_prop': 'The 20 candidacies that spent the most. {a} of {n} candidacies advertised.',
  'ads.nao_anunciou': 'no ads', 'ads.menos100': 'under R$ 100',
  'ads.destaques': 'Highlights', 'ads.destaques_leg': 'Generated from the figures above; descriptive, no interpretation.',
  'ads.d1': '{nome} ({cargo}, {partido}) is the candidacy that spent the most: {v}, {p} of all candidacy spending.',
  'ads.d2': 'Candidacies account for {p1} of political ad spending; governments and public bodies for {p2}.',
  'ads.d3': 'Among candidacies, the group that spent the most was {campo}: {v} ({p}).',
  'ads.d4': '{uf} accounts for {p} of total spending, the largest share of any state.',
  'ads.d5': 'In {uf}, the top advertiser is {nome} ({tipo}), with {v}.',
  'ads.d6': 'In the {cargo} race in {uf}, {a} of {n} candidacies advertised; {nome} accounts for {p} of the spending.',
  'ads.anuncios': 'Ads', 'ads.gasto_curto': 'Spend', 'ads.impressoes': 'Impressions', 'ads.citam_lula': 'Mention Lula',
  'ads.pagina': 'Page', 'ads.n_anuncios': '{n} ads', 'ads.n_paginas': '{n} pages', 'ads.n_cand': '{n} candidacies', 'ads.n_cand1': '1 candidacy',
  'ads.citam': 'Mention "{b}" in the text', 'ads.vazio': 'No ad data consolidated yet.',
  'ads.busca_titulo': 'Ads mentioning "{b}" (keyword search)',
  'ads.busca_aviso': 'Ads returned by a search for "{b}" (downloaded {d}), with delivery starting on or after {ini}. Spend and impressions come as ranges: the solid bar reaches the lower bound and the light part the upper bound.',
  'ads.b_quem': "Who uses Lula's name in ads", 'ads.b_quem_leg': 'Share of each bloc\'s ads with "Lula" in the text.',
  'ads.b_dia': 'Ads started per day, by bloc', 'ads.b_dia_leg': 'Delivery start day. Ads not matched to TSE are left out.',
  'ads.publico_de': 'Audience of', 'ads.todos': 'All ads',
  'ads.b_publico': 'Who saw them: age and gender', 'ads.b_publico_leg': "Share of impressions (midpoint of each ad's range).",
  'ads.b_regiao': 'Where they were seen', 'ads.b_regiao_leg': 'Share of impressions by state.',

  'met.nota': 'Bar: candidacies with an account in the census. Tick: declared an Instagram account to TSE.',
  'met.registradas': 'Registered', 'met.declarado': 'Declared Instagram', 'met.no_censo': 'In census', 'met.grupo': 'Group',
  'met.k_reg': 'Registered candidacies', 'met.k_reg_det': 'president, governor, senator and deputies',
  'met.k_censo': 'In the downloadable census', 'met.k_censo_det': '{p} of candidacies',
  'met.cargo': 'Coverage by office', 'met.cargo_leg': 'Share of TSE-registered candidacies that are in the census. Next to each group, the number of candidacies.',
  'met.genero': 'Coverage by gender', 'met.genero_leg': 'Share of candidacies in the census.',
  'met.raca': 'Coverage by race/colour', 'met.raca_leg': 'Self-reported to TSE; groups with 10 or more candidacies.',

  'ajuda.geral_posts': "Each line adds up the posts published that day by the candidate accounts of one bloc. Bloc is the presidential coalition of the candidate's party, taken from TSE registration records: an electoral alliance, not ideology.\n\nThe day is the UTC day, as in the Content Library filter. Brasília is UTC−3, so a post at 10 pm Brasília time falls on the next day.\n\nGrey bands mark days with no data: that week has not been downloaded yet. The most recent days come from a capture taken at 8:30 pm Brasília time on the same day; posts published between 8:30 and 9 pm are added when the full week is downloaded.",
  'ajuda.geral_veiculos': 'Daily posts by the 130 news outlet accounts in the census, national and regional. The weekend dips reflect newsroom routines.',
  'ajuda.geral_ativas': 'How many candidate accounts in the census published at least one post that day. It shows whether more posts come from more active accounts or from more posts per account.',
  'ajuda.geral_semanas': 'Publication weeks run Sunday to Saturday. The first runs from Saturday 15 Aug (a baseline day, the eve of campaigning) to 22 Aug.\n\nEach week is downloaded from the Content Library after it ends. The first three were downloaded later, when posts were already 15 to 29 days old; from 6 Sep on, posts are observed at 7 to 14 days. This matters for engagement, not for post counts.',
  'ajuda.perfis': 'One row per census account: candidates with 25,000 followers or a verification badge, party accounts and news outlets.\n\nMedians use the posts observed in the weekly download, 7 to 32 days after publication, and are shown only with 10 or more posts. Stories are excluded because they have no likes or comments.\n\nIn the profile card, peers are the accounts with the same office and bloc (or the same type, for outlets and parties). "2× the median" means twice the peer median. Topics come from the dashboard dictionary.',
  'ajuda.eng_mediana': "The median is the middle value: half of the posts have more and half have less. The thin line runs from the 1st quartile (25% of posts below) to the 3rd (75% below). The median is not pulled up by one or two viral posts.\n\nAge at observation: likes and comments keep growing after a post is published. Each week was observed at a given age: the first three at 15 to 29 days, the later ones at 7 to 14. Combining weeks mixes ages; compare blocs within the same selection, not weeks with each other.\n\nTo allow any combination of weeks, the dashboard stores each week's distribution in narrow bins and computes the median of the sum; the error is under 2%. Only groups with 10 or more posts are included.",
  'ajuda.eng_formato': 'The same median, split by post format: video (including reels), photo and carousel (album with several images). Stories are excluded because they have no likes or comments.',
  'ajuda.eng_horario': "For each bloc, the share of posts published in each hour of the day, Brasília time. Each curve adds up to 100%. It shows posting routines, not engagement.",
  'ajuda.eng_duas': "Some posts were seen twice: in the 8:30 pm capture on the day they were published (0 to 24 hours old) and later in the weekly download (7 to 14 days old). The ratio between the two counts shows how much of the week's engagement was already there on day one: 0.6 means 60%.\n\nIt is not an hour-by-hour growth curve; there are only two points per post. Posts that disappeared between the two downloads are not included.",
  'ajuda.temas_mapa': "Each cell is the share of the segment's posts whose caption mentions at least one word of the topic. A post can mention several topics.\n\nThe dictionary belongs to the dashboard (config/temas_painel.yaml), inspired by NetLab UFRJ's macro-categories, and is still under review. These are word counts: they do not tell whether a post supports or attacks, or whether the topic is central. Text inside images and videos is not included.",
  'ajuda.temas_mencoes': 'Share of posts mentioning each name or handle. "Bolsonaro (any)" counts any Bolsonaro: Jair, Flávio, Eduardo, Michelle. "STF / Moraes" combines the Supreme Court and Justice Moraes. Mentioning is not endorsing: the stance of each mention comes in the next phase.',
  'ajuda.temas_linha': 'The same share of posts mentioning the chosen name, week by week, for each bloc and for news outlets. The last week is incomplete until the weekly download.',
  'ajuda.temas_tags': "Most used hashtags by the segment's accounts in the chosen period. Only hashtags with 10 or more posts from 3 or more accounts are included.",
  'ajuda.conv_total': 'The public conversation is election-related posts from accounts outside the census, found by keyword in four searches: presidential candidates and the Supreme Court; political labels (petista, bolsonarista); election and voting (electoral court, voting machines, polls); and candidacies.\n\nPosts from census accounts and false positives ("lula" the squid, funeral urns) are left out. Each week is downloaded 7 days after it ends.',
  'ajuda.conv_mencoes': 'One chart per name, all on the same scale: the share of each day\'s posts that mention that name.\n\nSince the search itself uses these names, the total volume follows from the search design. What matters is the comparison between names and over time.',
  'ajuda.conv_agenda': "For each topic, the upper bar is the share of public conversation posts mentioning it; the lower bar, the share of candidates' posts in the same week. It shows what the public discusses more, or less, than candidates.\n\nThe conversation was found through election-related words, so it tends to talk more about politics and institutions.",
  'ajuda.conv_alta': 'The most used hashtags in the week and how much each changed from the previous week. "New" means the hashtag did not appear the week before. Only hashtags with 20 or more posts from 5 or more accounts.',
  'ajuda.conv_quem': 'Instagram classifies accounts as content creator, business or organisation, and personal. Format is the post format: video, photo, carousel or story.',
  'ajuda.ads_uf': "From Meta's public Ad Library report: how much was spent on ads about politics and elections seen in each state, by any advertiser (candidates, parties, governments, companies, organisations).\n\nThe state is where the ad was seen, not where the advertiser is. The period is the 90 days up to the report date, so it includes the pre-campaign. Meta does not detail pages that spent less than R$ 100.",
  'ajuda.ads_tipo': 'Each page was classified: candidacy (linked to a TSE candidacy through the campaign tax ID in "paid for by", the page name or its ads), party (the page name is a party), government (federal, state and city governments, ministries, legislatures, courts, public bodies and state companies) and other (companies, institutes, outlets, profiles not matched to a candidacy).\n\nCandidacies and parties are coloured by bloc. Spending belongs to the page, whoever paid: the person, the party or the campaign.',
  'ajuda.ads_top': 'The ten pages that spent the most on ads seen in the chosen state (for Brazil, the top fifteen). Colour is the bloc for candidacies and parties; grey for government and other.',
  'ajuda.ads_cargo': 'Sum of the spending of pages linked to candidacies, by office and bloc, across Brazil over the 90 days of the report.',
  'ajuda.ads_disputa': 'All candidacies registered with TSE for the chosen office and state, with the spending of the pages linked to each (across Brazil). Candidacies with no ads show "no ads". For deputies, the 20 that spent the most.\n\nLinking pages to candidacies is automatic and can fail: pages whose name differs from the ballot name may be missed, and namesakes in the same state may be confused.',
  'ajuda.ads_destaques': 'Sentences generated from the report figures, with no interpretation. They change with the chosen state and race.',
  'ajuda.busca': 'Individual ads returned by an Ad Library keyword search, with spend and impression ranges, audience by age and gender, and distribution by state. It is a sample: only ads that mention the term (in the text or another field) are included.',
  'ajuda.met_cobertura': 'Registered: candidacies with TSE (president, governor, senator and deputies). Declared Instagram: a profile was reported to TSE or found by search. In census: the account can be downloaded from the Content Library (25,000 followers or a verification badge) and posted during the sweep week.\n\nDifferences between groups show who is less visible in the data.',

  metodo: [
    ['What this dashboard is', 'An aggregated, descriptive picture of the Instagram activity of candidates, parties and news outlets in the 2026 campaign, updated with each new data collection. This is phase 0: counts, medians and dictionaries. Later phases add model-based labels validated against a human-coded sample.'],
    ['Where the data come from', [
      'Posts: Meta Content Library, CSV export of downloadable accounts (25,000 followers or a verification badge) of candidates, parties and 130 news outlets, checked against TSE records.',
      'Each publication week is downloaded after it ends; the most recent days come from a daily capture at 8:30 pm Brasília time, replaced by the weekly download when it arrives.',
      'Public conversation: keyword searches for accounts outside the census.',
      "Ads: Meta's public Ad Library report (spend by advertiser and by state) and keyword searches (individual ads).",
      'Candidacies, blocs and coalitions: public TSE files (14 Sep 2026).']],
    ['How to read it', [
      "Bloc is the presidential coalition of the candidate's party: an electoral alliance, not ideology.",
      'Days are in UTC, as in the Content Library filters; Brasília is UTC−3.',
      'Medians and quartiles are shown only with 10 or more posts; below that, "—".',
      'Topics and mentions are dictionary counts, with no model and no validation.',
      'The "?" buttons next to each chart explain how it is calculated.']],
    ['Caveats', [
      'The census is not a random sample: coverage is lower among women, Black, pardo and Indigenous candidates, non-incumbents and candidates from the North (charts above).',
      'Engagement depends on how old a post was when observed; compare within the same selection of weeks.',
      "About 9% of posts hide their like counts; each median's denominator is the number of posts with that metric.",
      'Data collection measures what survived until download, not everything that was published.',
      'Nothing here is causal.']],
    ['What is not here', 'Post text, post identifiers, links and media, Meta internal identifiers, and any per-account data for the public conversation line. Raw data stay with the researchers approved for the project.'],
    ['Terms of use', [
      'Restricted to the project group; do not share the password.',
      'Nothing is made public before the certification of elected candidates (diplomação) on 18 Dec 2026.',
      'When citing, credit the Meta Content Library and the Ad Library as sources, and TSE for candidacy data.']],
    ['Next phases', [
      'Sentiment, incivility and discourse function (acclaim, attack, defence) by model, with human validation.',
      'Who talks about whom, with the stance (favourable, unfavourable, neutral) of each mention.',
      'Topics per profile and emerging topics; model-based topics in the same categories as the dictionary.',
      'Engagement models with account fixed effects (rate ratios and odds ratios).']],
  ],
},
};
